name: Lint
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-wasm32
      GITHUB_OWNER: "emscripten-forge"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci_env.yml
          cache-environment: true


      - name: Lint check
        shell: bash -l {0}
        run: |
          pre-commit run --all-files --show-diff-on-failure
