name: Run some simple tests on empack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  test_empack:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: "emscripten-forge"

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.2"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '0.25.1'

      - name: Install empack
        shell: bash -l {0}
        run: |
          pip install .

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -v -s tests/

      - name: Install emsdk
        shell: bash -l {0}
        run: |
          emsdk install ${{ matrix.emsdk_ver }}
          emsdk activate ${{ matrix.emsdk_evr }}

      - name: Run smoke tests
        shell: bash -l {0}
        run: |
          empack --help
          empack pack --help

      - name: Create Python env and pack it up
        shell: bash -l {0}
        run: |
          micromamba create -n env1 -c https://repo.mamba.pm/emscripten-forge --platform=emscripten-32 python

          emsdk activate ${{ matrix.emsdk_ver }}
          source $CONDA_EMSDK_DIR/emsdk_env.sh

          empack pack env \
            --env-prefix $MAMBA_ROOT_PREFIX/envs/env1 \
            --outname env_1 \
            --config $GITHUB_WORKSPACE/tests/empack_test_config.yaml

          if [ ! -f "env_1.js" ]; then
            echo "env_1.js is missing"
            exit 1
          fi
          if [ ! -f "env_1.data" ]; then
            echo "env_1.data is missing"
            exit 1
          fi

          empack pack inspect -j env_1.js 

          empack pack env \
            --env-prefix $MAMBA_ROOT_PREFIX/envs/env1 \
            --outname env_2 \
            --config $GITHUB_WORKSPACE/tests/empack_test_config.yaml \
            --config $GITHUB_WORKSPACE/tests/empack_test_extra_config.yaml \
            --split

          if [ ! -f "env_2.js" ]; then
            echo "env_2.js is missing"
            exit 1
          fi
          if [-f "env_2.data" ]; then
            echo "env_2.data is present but should not be there!"
            exit 1
          fi


      - name: Create another lib-only env and pack it up
        shell: bash -l {0}
        run: |
          micromamba create -n env2 -c https://repo.mamba.pm/emscripten-forge --platform=emscripten-32 eigen

          emsdk activate ${{ matrix.emsdk_ver }}
          source $CONDA_EMSDK_DIR/emsdk_env.sh

          empack pack env \
            --env-prefix $MAMBA_ROOT_PREFIX/envs/env2 \
            --outname env_2 \
            --config $GITHUB_WORKSPACE/tests/empack_test_config.yaml

          if [ ! -f "env_2.js" ]; then
            echo "env_2.js is missing"
            exit 1
          fi
          if [ ! -f "env_2.data" ]; then
            echo "env_2.data is missing"
            exit 1
          fi


          empack pack env \
            -c $GITHUB_WORKSPACE/tests/empack_test_config.yaml \
            -e $MAMBA_ROOT_PREFIX/envs/env2 \
            -o env_2_b \

          if [ ! -f "env_2_b.js" ]; then
            echo "env_2_b.js is missing"
            exit 1
          fi
          if [ ! -f "env_2_b.data" ]; then
            echo "env_2_b.data is missing"
            exit 1
          fi
