name: Run some simple tests on empack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  test_empack_unix:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: "emscripten-forge"

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '1.4.1'

      - name: Install empack
        shell: bash -l {0}
        run: |
          pip install .

      - name: Install Playwright
        shell: bash -l {0}
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/emscripten-forge/pyjs-code-runner@main  --no-deps --ignore-installed

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -v -s tests/

      - name: Run cli from terminal
        shell: bash -l {0}
        run: |
          empack --help
          empack pack --help

  test_empack_windows:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v2

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '1.4.1'

 

      - name: Install empack
        shell: cmd /C CALL {0}
        run: >-
          pip install .

      - name: Install Playwright
        shell: powershell
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: cmd /C CALL {0}
        run: >-
          python -m pip install git+https://github.com/emscripten-forge/pyjs-code-runner@main  --no-deps --ignore-installed

      - name: Run pytest
        shell: cmd /C CALL {0}
        run: >-
          pytest -v -s tests/

      - name: Run cli from terminal
        shell: cmd /C CALL {0}
        run: >-
          empack pack --help

