name: test empack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  build_recipes:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: "emscripten-forge"

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.2"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '0.25.1'

      - name: install emsdk
        shell: bash -l {0}
        run: |
          micromamba activate ci-env
          emsdk install ${{matrix.emsdk_ver}}

      - name: "install custom non-master dependencies"
        shell: bash -l {0}
        run: |
          micromamba activate ci-env
          pip install .

      - name: "Run smoke tests"
        shell: bash -l {0}
        run: |
          empack --help
          empack pack --help

      - name: "Create env and pack it up"
        shell: bash -l {0}
        run: |
          micromamba create -n env1 -c https://repo.mamba.pm/emscripten-forge --platform=emscripten-32 python
          empack pack python core $MAMBA_ROOT_PREFIX/envs/env1 --version=3.10

      - name: "Create another env and pack it up"
        shell: bash -l {0}
        run: |
          micromamba create -n env2 -c https://repo.mamba.pm/emscripten-forge --platform=emscripten-32 eigen
          empack pack python core $MAMBA_ROOT_PREFIX/envs/env2 --version=3.10
