name: Run some simple tests on empack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  test_empack:


    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, 	macos-latest]

    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: "emscripten-forge"

    strategy:

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '1.4.1'

      - name: Install empack
        shell: bash -l {0}
        run: |
          pip install .

      - name: Install Playwright
        shell: bash -l {0}
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/emscripten-forge/pyjs-code-runner@main  --no-deps --ignore-installed

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -v -s tests/

      - name: Run cli from terminal
        shell: bash -l {0}
        run: |
          empack --help
          empack pack --help

win:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '1.4.1'

      - name: micromamba shell hook
        shell: powershell
        run: |
          micromamba shell hook -s cmd.exe -p C:\Users\runneradmin\micromamba-root

      - name: Install empack
        shell: cmd
        run: |
          pip install .

      - name: Install Playwright
        shell: cmd
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/emscripten-forge/pyjs-code-runner@main  --no-deps --ignore-installed
          
      - name: Run pytest
        shell: cmd
        run: |
          pytest -v -s tests/

      - name: Run cli from terminal
        shell: cmd
        run: |
          empack --help
          empack pack --help

