name: Run some simple tests on empack
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  test_empack:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: "emscripten-forge"

    strategy:
      fail-fast: false

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mamba and dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '1.4.1'

      - name: Install empack
        shell: bash -l {0}
        run: |
          pip install .

      - name: Install Playwright
        shell: bash -l {0}
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/DerThorsten/pyjs-code-runner@relocate_env   --no-deps --ignore-installed

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -v -s tests/

      - name: Run smoke tests
        shell: bash -l {0}
        run: |
          empack --help
          empack pack --help